sudo: required
language: node_js
node_js:
- '7'
before_install:
- docker build -t $DOCKER_REPO .
- docker run -p 5000:5000 -d $DOCKER_REPO
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 0.23.2
- export PATH="$HOME/.yarn/bin:$PATH"
- export CHROME_BIN=/usr/bin/google-chrome
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sudo apt-get update
- sudo apt-get install -y libappindicator1 fonts-liberation
- wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
- sudo dpkg -i google-chrome*.deb
cache: yarn
script:
- yarn flow
- yarn lint
- yarn docs
- yarn test
- yarn report-coverage
- yarn pa11y
- yarn sitespeed
- yarn cucumber
- yarn prod-firebase
- yarn firebase-deploy
services:
- docker
after_success:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
- test "$TRAVIS_BRANCH" = "master" && docker push $DOCKER_REPO;
- test "$TRAVIS_BRANCH" = "master" && sh ./travis/deploy_heroku.sh
notifications:
  slack:
    secure: k/tJMcUD85O/5t3DN2KwnNLRPpHZpyK8hnhNz9gElhQ8Zg5hNMjwuC0nyNdj8+XNZMqHJUftg+LADxGV0pXXV7G5bGisWeXWzTd1cmzed0UzlJDyTNEnTT/LeNI/0e8ckmvtold67oH5X7TrUH4Mr9RTu6RY2iyxCKB6IGbs6BsM5CijiU6gtyptVn1dT1Xq6YVJfNl2G4R+/UEiYHbpNNDNJ2k9poTFswQwymR+5zeeYUYpQ4hg2uNVBE6ZSk4Nn9mMN7Bv9JM75MlgD9I4M8Nrfyen9LnGCsie9C9J6ZtDFmLFeOodYlQQc1o7FzRptQ98eTrrTxOnl1v5za9sbfhRfj2yt9YiEoLVhyWloYeBP+r8/rJRSDa9H4/NMhdAGgs5S9x0fWDo2FN6bTChpT9OdsLyoCX6haonrZEBrqi3bbvdAbtu5XwcDPwtIRrQ+/O4PH/fBqwGwI1Ak+K14Tr9UC1UaJix9u760FlpwXkP4WvQFdp0QzIGyV4nDT9NExiVFED01Tfp1uPWcpkKIJE3zizFz1kgayM9w1w/dUvhSaWi/S1GtNPmXPW4LR+U+cyzk8VgNh5OS3UFW6LIE31hbOO8dzhXDMha7JCOBgsZe2Xl6JY9xYce5KGJkhU/9JdcU5zr9LVYr4gXwAuJoaZ62f6SFxTK9lTANTk867U=
